### PR TITLE
- Added countrieList function support.

### PR DESCRIPTION
**Pull request by rroshan91**
- When no arguments passed, then it will return complete list.
- When one argument is passed then the only country name specific to the
key is returned.
- When multiple arguments are passed, then it will return key value pair
of all keys.

### CODE REVIEW

**Comment by vincentrussell** [comment]
Can you make sure that files that you change are formatted with the following code style:

https://github.com/vincentrussell/json-data-generator/tree/master/src/test/resources/code-style

it just looks like the entire files are changing with the merge.

**Comment by rroshan91** [comment]
Done formatted the code

**Comment by vincentrussell** [comment]
Please make sure you run mvn verify to make sure all of the checkstyle rules pass.
Thanks,

**Comment by rroshan91** [comment]
Sure I'll take of running mvn verify before creating pull request.

**Pull request merged**
