### PR TITLE
Added check for invalid scenarios to avoid going in infinite loop

### PR DESCRIPTION
**Pull request by Paridhi25**

### CODE REVIEW

**Comment by Paridhi25** [comment]
If "{{" template is given , the code was throwing out of memory exception. So added one check to address the issue. 
Added the junits for the same.

**Comment by Paridhi25** [comment]
Also, i observed one more issue, if a constant is given as a open or close curly braces, the function dont work. e.g.
{{concat("a", "test", "b")}} work and gives result "atestb"
{{concat("{", "test", "}")}} dont work and gives the same string back.

Can you please add support for that.

**Comment by vincentrussell** [comment]
ok.  hopefully I will have time to work on this this weekend.

**Comment by Paridhi25** [comment]
Vincent, can you please merge this PR, its a small changes and i have added junits too.

**Comment by vincentrussell** [comment]
ok merged.  Do you need another release?

**Comment by Paridhi25** [comment]
Yes, i will be needing another release.

**Comment by vincentrussell** [comment]
ok.   I released this as 1.4.1

**Comment by Paridhi25** [comment]
Thankyou..can you also provide the fix for '{' and '}'.

**Comment by vincentrussell** [comment]
when you said the and problem do you mean: 

{{concat("{", "test", "}")}} dont work and gives the same string back.?

**Comment by Paridhi25** [comment]
yeah, i meant the same:
{{concat("{", "test", "}")}} dont work and gives the same string back.

**Comment by vincentrussell** [comment]
You can now do this by escaping the brace characters:

{{concat("\{", "test", "\}")}}

Thanks for finding the bug.

**Comment by vincentrussell** [comment]
{{concat("\\{", "test", "\\}")}}

**Pull request merged**
