### PR TITLE
- Added countrieList function support.

### PR DESCRIPTION
**Pull request by rroshan91**
- When no arguments passed, then it will return complete list.
- When one argument is passed then the only country name specific to the
key is returned.
- When multiple arguments are passed, then it will return key value pair
of all keys.

This function is available at: https://www.json-generator.com/

### CODE REVIEW

**Comment by vincentrussell** [comment]
Can you rebase this against master?  You will have to resolve some conflicts.

Thanks,

**Comment by rroshan91** [comment]
Resolved the merge conflict.

**Comment by vincentrussell** [comment]
can you redo the pull request maybe?  It doesn't look like I can merge this.

**Comment by rroshan91** [comment]
what is the issue that I need to fix to merge the pull request?

**Comment by vincentrussell** [comment]
you need to rebase against my repo's master.  Is your fork up to date with my repo?

**Comment by rroshan91** [comment]
Created new CR: https://github.com/vincentrussell/json-data-generator/pull/10

**Pull request closed without merging**
